const mongoose = require('mongoose');

const rentalBillingSchema = new mongoose.Schema({
  // Tenant Information
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'RentalApplication',
    required: true
  },
  tenantName: {
    type: String,
    required: true
  },
  tenantEmail: {
    type: String,
    required: true
  },
  property: {
    type: String,
    required: true
  },

  // Billing Period
  billingMonth: {
    type: Number, // 1-12
    required: true
  },
  billingYear: {
    type: Number,
    required: true
  },

  // Amounts
  rentAmount: {
    type: Number,
    required: true
  },
  lateFee: {
    type: Number,
    default: 0
  },
  otherCharges: {
    type: Number,
    default: 0
  },
  otherChargesDescription: {
    type: String
  },
  totalAmount: {
    type: Number,
    required: true
  },
  amountPaid: {
    type: Number,
    default: 0
  },
  balance: {
    type: Number,
    required: true
  },

  // Status
  status: {
    type: String,
    enum: ['pending', 'sent', 'paid', 'partial', 'overdue', 'cancelled'],
    default: 'pending'
  },

  // Important Dates
  dueDate: {
    type: Date,
    required: true
  },
  invoiceSentDate: {
    type: Date
  },
  paidDate: {
    type: Date
  },
  lateAfterDate: {
    type: Date // 5 days after due date
  },

  // Payment Information
  payments: [{
    amount: { type: Number, required: true },
    paymentMethod: { type: String, enum: ['cash', 'check', 'bank_transfer', 'card'] },
    paymentDate: { type: Date, required: true },
    checkNumber: { type: String },
    transactionId: { type: String },
    notes: { type: String },
    recordedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    recordedAt: { type: Date, default: Date.now }
  }],

  // Reminders
  remindersSent: [{
    type: { type: String, enum: ['due_soon', 'overdue', 'late_fee'] },
    sentDate: { type: Date },
    method: { type: String, enum: ['email', 'sms', 'both'] }
  }],

  // Notes
  adminNotes: {
    type: String
  },

  // Automation flags
  autoGenerated: {
    type: Boolean,
    default: false
  },
  autoSent: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

// Indexes
rentalBillingSchema.index({ tenantId: 1, billingYear: 1, billingMonth: 1 });
rentalBillingSchema.index({ status: 1, dueDate: 1 });
rentalBillingSchema.index({ dueDate: 1 });

// Calculate total amount
rentalBillingSchema.pre('save', function(next) {
  this.totalAmount = this.rentAmount + this.lateFee + this.otherCharges;
  this.balance = this.totalAmount - this.amountPaid;

  // Update status based on balance
  if (this.balance === 0) {
    this.status = 'paid';
    if (!this.paidDate) {
      this.paidDate = new Date();
    }
  } else if (this.amountPaid > 0) {
    this.status = 'partial';
  } else if (new Date() > this.lateAfterDate) {
    this.status = 'overdue';
  } else if (this.invoiceSentDate) {
    this.status = 'sent';
  }

  next();
});

// Method to add payment
rentalBillingSchema.methods.addPayment = function(paymentData) {
  this.payments.push(paymentData);
  this.amountPaid += paymentData.amount;
  return this.save();
};

// Method to apply late fee
rentalBillingSchema.methods.applyLateFee = function(lateFeeAmount = 50) {
  if (this.lateFee === 0 && this.status !== 'paid') {
    this.lateFee = lateFeeAmount;
    return this.save();
  }
  return Promise.resolve(this);
};

module.exports = mongoose.model('RentalBilling', rentalBillingSchema);
