const RentalBilling = require('../models/rentalBilling');
const RentalApplication = require('../models/rentalApplication');
const { sendEmail } = require('../utils/emailservice');

// Generate monthly rent invoice for a tenant
exports.generateMonthlyInvoice = async (req, res) => {
  try {
    const { tenantId, month, year } = req.body;

    // Get tenant information from rental application
    const tenant = await RentalApplication.findById(tenantId);

    if (!tenant) {
      return res.status(404).json({
        success: false,
        message: 'Tenant not found'
      });
    }

    if (tenant.status !== 'contract_sent' && tenant.status !== 'approved') {
      return res.status(400).json({
        success: false,
        message: 'Tenant must have an active contract'
      });
    }

    // Check if invoice already exists for this period
    const existingInvoice = await RentalBilling.findOne({
      tenantId,
      billingMonth: month,
      billingYear: year
    });

    if (existingInvoice) {
      return res.status(400).json({
        success: false,
        message: 'Invoice already exists for this billing period',
        data: existingInvoice
      });
    }

    // Calculate dates
    const dueDate = new Date(year, month - 1, 1); // 1st of the month
    const lateAfterDate = new Date(year, month - 1, 6); // 6th of the month (5-day grace period)

    // Create invoice
    const invoice = new RentalBilling({
      tenantId,
      tenantName: `${tenant.personalInfo.firstName} ${tenant.personalInfo.lastName}`,
      tenantEmail: tenant.personalInfo.email,
      property: tenant.property,
      billingMonth: month,
      billingYear: year,
      rentAmount: tenant.offerAmount,
      totalAmount: tenant.offerAmount,
      balance: tenant.offerAmount,
      dueDate,
      lateAfterDate,
      autoGenerated: true
    });

    await invoice.save();

    // Send invoice email
    try {
      const invoiceEmailHTML = getInvoiceEmail(invoice);
      await sendEmail({
        to: tenant.personalInfo.email,
        subject: `Rent Invoice for ${getMonthName(month)} ${year} - M77 AG`,
        html: invoiceEmailHTML
      });
      invoice.invoiceSentDate = new Date();
      invoice.status = 'sent';
      invoice.autoSent = true;
      await invoice.save();
    } catch (emailError) {
      console.error('Error sending invoice email:', emailError);
    }

    res.status(201).json({
      success: true,
      message: 'Invoice generated successfully',
      data: invoice
    });
  } catch (error) {
    console.error('Error generating invoice:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate invoice',
      error: error.message
    });
  }
};

// Auto-generate invoices for all active tenants
exports.autoGenerateInvoices = async (req, res) => {
  try {
    const { month, year } = req.body;
    const currentMonth = month || new Date().getMonth() + 1;
    const currentYear = year || new Date().getFullYear();

    // Find all approved tenants with active contracts
    const activeTenants = await RentalApplication.find({
      status: { $in: ['contract_sent', 'approved'] },
      leaseStartDate: { $lte: new Date() }
    });

    const results = [];
    const errors = [];

    for (const tenant of activeTenants) {
      try {
        // Check if lease is still active
        if (tenant.leaseEndDate && new Date(tenant.leaseEndDate) < new Date()) {
          continue; // Skip expired leases
        }

        // Check if invoice already exists
        const existingInvoice = await RentalBilling.findOne({
          tenantId: tenant._id,
          billingMonth: currentMonth,
          billingYear: currentYear
        });

        if (existingInvoice) {
          continue; // Skip if invoice already exists
        }

        // Calculate dates
        const dueDate = new Date(currentYear, currentMonth - 1, 1);
        const lateAfterDate = new Date(currentYear, currentMonth - 1, 6);

        // Create invoice
        const invoice = new RentalBilling({
          tenantId: tenant._id,
          tenantName: `${tenant.personalInfo.firstName} ${tenant.personalInfo.lastName}`,
          tenantEmail: tenant.personalInfo.email,
          property: tenant.property,
          billingMonth: currentMonth,
          billingYear: currentYear,
          rentAmount: tenant.offerAmount,
          totalAmount: tenant.offerAmount,
          balance: tenant.offerAmount,
          dueDate,
          lateAfterDate,
          autoGenerated: true
        });

        await invoice.save();

        // Send invoice email
        try {
          const invoiceEmailHTML = getInvoiceEmail(invoice);
          await sendEmail({
            to: tenant.personalInfo.email,
            subject: `Rent Invoice for ${getMonthName(currentMonth)} ${currentYear} - M77 AG`,
            html: invoiceEmailHTML
          });
          invoice.invoiceSentDate = new Date();
          invoice.status = 'sent';
          invoice.autoSent = true;
          await invoice.save();
        } catch (emailError) {
          console.error(`Error sending invoice email to ${tenant.personalInfo.email}:`, emailError);
        }

        results.push({
          tenant: `${tenant.personalInfo.firstName} ${tenant.personalInfo.lastName}`,
          invoiceId: invoice._id,
          amount: invoice.rentAmount
        });
      } catch (error) {
        errors.push({
          tenant: `${tenant.personalInfo.firstName} ${tenant.personalInfo.lastName}`,
          error: error.message
        });
      }
    }

    res.status(200).json({
      success: true,
      message: `Generated ${results.length} invoices`,
      data: {
        generated: results,
        errors: errors,
        month: getMonthName(currentMonth),
        year: currentYear
      }
    });
  } catch (error) {
    console.error('Error auto-generating invoices:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to auto-generate invoices',
      error: error.message
    });
  }
};

// Record a payment
exports.recordPayment = async (req, res) => {
  try {
    const { invoiceId } = req.params;
    const { amount, paymentMethod, paymentDate, checkNumber, transactionId, notes } = req.body;

    const invoice = await RentalBilling.findById(invoiceId);

    if (!invoice) {
      return res.status(404).json({
        success: false,
        message: 'Invoice not found'
      });
    }

    const paymentData = {
      amount: parseFloat(amount),
      paymentMethod,
      paymentDate: paymentDate || new Date(),
      checkNumber,
      transactionId,
      notes,
      recordedBy: req.user ? req.user._id : null
    };

    await invoice.addPayment(paymentData);

    // Send payment confirmation email
    try {
      const confirmationEmailHTML = getPaymentConfirmationEmail(invoice, paymentData);
      await sendEmail({
        to: invoice.tenantEmail,
        subject: `Payment Received - ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} Rent`,
        html: confirmationEmailHTML
      });
    } catch (emailError) {
      console.error('Error sending payment confirmation email:', emailError);
    }

    res.status(200).json({
      success: true,
      message: 'Payment recorded successfully',
      data: invoice
    });
  } catch (error) {
    console.error('Error recording payment:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to record payment',
      error: error.message
    });
  }
};

// Get all invoices
exports.getAllInvoices = async (req, res) => {
  try {
    const { status, year, month, tenantId } = req.query;

    const filter = {};
    if (status) filter.status = status;
    if (year) filter.billingYear = parseInt(year);
    if (month) filter.billingMonth = parseInt(month);
    if (tenantId) filter.tenantId = tenantId;

    const invoices = await RentalBilling.find(filter)
      .sort({ billingYear: -1, billingMonth: -1 })
      .lean();

    res.status(200).json({
      success: true,
      count: invoices.length,
      data: invoices
    });
  } catch (error) {
    console.error('Error fetching invoices:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch invoices',
      error: error.message
    });
  }
};

// Get single invoice
exports.getInvoiceById = async (req, res) => {
  try {
    const { id } = req.params;

    const invoice = await RentalBilling.findById(id)
      .populate('tenantId', 'personalInfo property')
      .lean();

    if (!invoice) {
      return res.status(404).json({
        success: false,
        message: 'Invoice not found'
      });
    }

    res.status(200).json({
      success: true,
      data: invoice
    });
  } catch (error) {
    console.error('Error fetching invoice:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch invoice',
      error: error.message
    });
  }
};

// Apply late fees to overdue invoices
exports.applyLateFees = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Find all invoices that are overdue and don't have late fees yet
    const overdueInvoices = await RentalBilling.find({
      status: { $in: ['sent', 'partial'] },
      lateAfterDate: { $lt: today },
      lateFee: 0
    });

    const results = [];

    for (const invoice of overdueInvoices) {
      await invoice.applyLateFee(50); // $50 late fee

      // Send late fee notification
      try {
        const lateFeeEmailHTML = getLateFeeEmail(invoice);
        await sendEmail({
          to: invoice.tenantEmail,
          subject: `Late Fee Applied - ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} Rent`,
          html: lateFeeEmailHTML
        });

        invoice.remindersSent.push({
          type: 'late_fee',
          sentDate: new Date(),
          method: 'email'
        });
        await invoice.save();
      } catch (emailError) {
        console.error('Error sending late fee email:', emailError);
      }

      results.push({
        tenant: invoice.tenantName,
        invoiceId: invoice._id,
        lateFee: 50
      });
    }

    res.status(200).json({
      success: true,
      message: `Applied late fees to ${results.length} invoices`,
      data: results
    });
  } catch (error) {
    console.error('Error applying late fees:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to apply late fees',
      error: error.message
    });
  }
};

// Send payment reminders
exports.sendPaymentReminders = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Find invoices that are due soon (within 3 days) or overdue
    const upcomingDue = new Date(today);
    upcomingDue.setDate(upcomingDue.getDate() + 3);

    const invoicesNeedingReminder = await RentalBilling.find({
      status: { $in: ['sent', 'partial'] },
      $or: [
        { dueDate: { $lte: upcomingDue, $gte: today } },
        { lateAfterDate: { $lt: today } }
      ]
    });

    const results = [];

    for (const invoice of invoicesNeedingReminder) {
      const isOverdue = invoice.lateAfterDate < today;
      const reminderType = isOverdue ? 'overdue' : 'due_soon';

      // Check if reminder already sent recently (within 3 days)
      const recentReminder = invoice.remindersSent.find(r =>
        r.type === reminderType &&
        new Date(r.sentDate) > new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000)
      );

      if (recentReminder) {
        continue; // Skip if reminder already sent recently
      }

      // Send reminder email
      try {
        const reminderEmailHTML = getReminderEmail(invoice, isOverdue);
        await sendEmail({
          to: invoice.tenantEmail,
          subject: isOverdue
            ? `Overdue Rent Notice - ${getMonthName(invoice.billingMonth)} ${invoice.billingYear}`
            : `Rent Payment Reminder - Due ${invoice.dueDate.toLocaleDateString()}`,
          html: reminderEmailHTML
        });

        invoice.remindersSent.push({
          type: reminderType,
          sentDate: new Date(),
          method: 'email'
        });
        await invoice.save();

        results.push({
          tenant: invoice.tenantName,
          invoiceId: invoice._id,
          type: reminderType
        });
      } catch (emailError) {
        console.error('Error sending reminder email:', emailError);
      }
    }

    res.status(200).json({
      success: true,
      message: `Sent ${results.length} payment reminders`,
      data: results
    });
  } catch (error) {
    console.error('Error sending payment reminders:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to send payment reminders',
      error: error.message
    });
  }
};

// Helper Functions

function getMonthName(month) {
  const months = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  return months[month - 1];
}

function getInvoiceEmail(invoice) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Rent Invoice</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; overflow: hidden;">
          <tr>
            <td style="background: linear-gradient(135deg, #2d5016 0%, #1a3009 100%); padding: 40px 30px; text-align: center;">
              <h1 style="color: #d4af37; margin: 0; font-size: 32px;">M77 AG</h1>
              <p style="color: white; margin: 10px 0 0 0; font-size: 18px;">Rent Invoice</p>
            </td>
          </tr>
          <tr>
            <td style="padding: 40px 30px;">
              <h2 style="color: #1a1a1a; margin: 0 0 20px 0;">Dear ${invoice.tenantName},</h2>
              <p style="color: #666; line-height: 1.6; margin-bottom: 25px;">
                Your rent invoice for ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} is now available.
              </p>

              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
                <h3 style="color: #2d5016; margin: 0 0 15px 0;">Invoice Details</h3>
                <table width="100%" cellpadding="8" cellspacing="0">
                  <tr>
                    <td style="color: #666;">Property:</td>
                    <td style="color: #1a1a1a; font-weight: 600;">${invoice.property}</td>
                  </tr>
                  <tr>
                    <td style="color: #666;">Billing Period:</td>
                    <td style="color: #1a1a1a;">${getMonthName(invoice.billingMonth)} ${invoice.billingYear}</td>
                  </tr>
                  <tr>
                    <td style="color: #666;">Due Date:</td>
                    <td style="color: #1a1a1a; font-weight: 600;">${invoice.dueDate.toLocaleDateString()}</td>
                  </tr>
                  <tr style="background: white;">
                    <td style="color: #666; padding-top: 15px; border-top: 2px solid #e0e0e0;">Monthly Rent:</td>
                    <td style="color: #1a1a1a; padding-top: 15px; border-top: 2px solid #e0e0e0;">$${invoice.rentAmount.toFixed(2)}</td>
                  </tr>
                  ${invoice.lateFee > 0 ? `
                  <tr>
                    <td style="color: #d32f2f;">Late Fee:</td>
                    <td style="color: #d32f2f;">$${invoice.lateFee.toFixed(2)}</td>
                  </tr>
                  ` : ''}
                  ${invoice.otherCharges > 0 ? `
                  <tr>
                    <td style="color: #666;">${invoice.otherChargesDescription || 'Other Charges'}:</td>
                    <td style="color: #1a1a1a;">$${invoice.otherCharges.toFixed(2)}</td>
                  </tr>
                  ` : ''}
                  <tr style="background: linear-gradient(135deg, #2d5016 0%, #1a3009 100%);">
                    <td style="color: #d4af37; font-weight: 700; font-size: 16px; padding: 12px 8px;">Total Due:</td>
                    <td style="color: white; font-weight: 700; font-size: 20px; padding: 12px 8px;">$${invoice.totalAmount.toFixed(2)}</td>
                  </tr>
                </table>
              </div>

              <div style="background: #fff4e6; border-left: 4px solid #d4af37; padding: 20px; margin-bottom: 25px;">
                <h3 style="color: #1a1a1a; margin: 0 0 10px 0; font-size: 16px;">Payment Options</h3>
                <ul style="color: #666; line-height: 1.8; margin: 0; padding-left: 20px;">
                  <li><strong>Check:</strong> Make payable to "M77 AG"</li>
                  <li><strong>Cash:</strong> Pay in person at our office</li>
                  <li><strong>Bank Transfer:</strong> Contact office@m77ag.com for details</li>
                </ul>
                <p style="color: #666; margin: 15px 0 0 0; font-size: 13px;">
                  <strong>Grace Period:</strong> Payment received by ${invoice.lateAfterDate.toLocaleDateString()} will not incur late fees.
                </p>
              </div>

              <p style="color: #666; line-height: 1.6; margin-top: 25px;">
                If you have any questions about this invoice, please contact us at office@m77ag.com or (970) 520-1807.
              </p>
              <p style="color: #666; line-height: 1.6; margin: 0;">
                Thank you for your tenancy!<br>
                <strong>M77 AG Property Management</strong>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

function getPaymentConfirmationEmail(invoice, payment) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Payment Received</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px;">
          <tr>
            <td style="background: linear-gradient(135deg, #2d5016 0%, #1a3009 100%); padding: 40px 30px; text-align: center;">
              <h1 style="color: #d4af37; margin: 0; font-size: 32px;">Payment Received</h1>
              <p style="color: white; margin: 10px 0 0 0;">Thank you for your payment!</p>
            </td>
          </tr>
          <tr>
            <td style="padding: 40px 30px;">
              <h2 style="color: #1a1a1a; margin: 0 0 20px 0;">Dear ${invoice.tenantName},</h2>
              <p style="color: #666; line-height: 1.6; margin-bottom: 25px;">
                We have received your rent payment for ${getMonthName(invoice.billingMonth)} ${invoice.billingYear}.
              </p>

              <div style="background: #e8f5e9; padding: 20px; border-radius: 8px; margin-bottom: 25px; text-align: center;">
                <p style="color: #2d5016; margin: 0 0 10px 0; font-size: 14px;">Payment Amount</p>
                <p style="color: #2d5016; margin: 0; font-size: 32px; font-weight: 700;">$${payment.amount.toFixed(2)}</p>
              </div>

              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
                <h3 style="color: #2d5016; margin: 0 0 15px 0;">Payment Details</h3>
                <table width="100%" cellpadding="8" cellspacing="0">
                  <tr>
                    <td style="color: #666;">Payment Date:</td>
                    <td style="color: #1a1a1a;">${new Date(payment.paymentDate).toLocaleDateString()}</td>
                  </tr>
                  <tr>
                    <td style="color: #666;">Payment Method:</td>
                    <td style="color: #1a1a1a;">${payment.paymentMethod.replace('_', ' ').toUpperCase()}</td>
                  </tr>
                  ${payment.checkNumber ? `
                  <tr>
                    <td style="color: #666;">Check Number:</td>
                    <td style="color: #1a1a1a;">${payment.checkNumber}</td>
                  </tr>
                  ` : ''}
                  <tr style="background: white;">
                    <td style="color: #666; padding-top: 15px; border-top: 2px solid #e0e0e0;">Remaining Balance:</td>
                    <td style="color: #1a1a1a; font-weight: 700; padding-top: 15px; border-top: 2px solid #e0e0e0;">$${invoice.balance.toFixed(2)}</td>
                  </tr>
                </table>
              </div>

              ${invoice.balance === 0 ? `
                <div style="background: #e8f5e9; border-left: 4px solid #2d5016; padding: 15px; margin-bottom: 20px;">
                  <p style="color: #2d5016; margin: 0; font-weight: 600;">
                    ✓ Your account is paid in full. Thank you!
                  </p>
                </div>
              ` : ''}

              <p style="color: #666; line-height: 1.6; margin-top: 25px;">
                If you have any questions, please contact us at office@m77ag.com or (970) 520-1807.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

function getLateFeeEmail(invoice) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Late Fee Applied</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px;">
          <tr>
            <td style="background: linear-gradient(135deg, #d32f2f 0%, #c62828 100%); padding: 40px 30px; text-align: center;">
              <h1 style="color: white; margin: 0; font-size: 28px;">Late Fee Notice</h1>
            </td>
          </tr>
          <tr>
            <td style="padding: 40px 30px;">
              <h2 style="color: #1a1a1a; margin: 0 0 20px 0;">Dear ${invoice.tenantName},</h2>
              <p style="color: #666; line-height: 1.6; margin-bottom: 25px;">
                Your rent payment for ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} is overdue.
                A late fee of $${invoice.lateFee.toFixed(2)} has been applied to your account.
              </p>

              <div style="background: #ffebee; padding: 20px; border-radius: 8px; margin-bottom: 25px; border-left: 4px solid #d32f2f;">
                <h3 style="color: #d32f2f; margin: 0 0 15px 0;">Updated Balance</h3>
                <table width="100%" cellpadding="8" cellspacing="0">
                  <tr>
                    <td style="color: #666;">Original Rent:</td>
                    <td style="color: #1a1a1a;">$${invoice.rentAmount.toFixed(2)}</td>
                  </tr>
                  <tr>
                    <td style="color: #d32f2f;">Late Fee:</td>
                    <td style="color: #d32f2f;">$${invoice.lateFee.toFixed(2)}</td>
                  </tr>
                  <tr style="background: white;">
                    <td style="color: #666; font-weight: 700; padding-top: 12px; border-top: 2px solid #d32f2f;">Total Due:</td>
                    <td style="color: #d32f2f; font-weight: 700; font-size: 20px; padding-top: 12px; border-top: 2px solid #d32f2f;">$${invoice.totalAmount.toFixed(2)}</td>
                  </tr>
                </table>
              </div>

              <p style="color: #666; line-height: 1.6; margin-bottom: 15px;">
                <strong>Please submit payment immediately to avoid further late fees.</strong>
              </p>

              <p style="color: #666; line-height: 1.6;">
                If you have any questions or need to discuss payment arrangements, please contact us immediately at
                office@m77ag.com or (970) 520-1807.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

function getReminderEmail(invoice, isOverdue) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Payment Reminder</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; background-color: #f5f5f5;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px;">
          <tr>
            <td style="background: linear-gradient(135deg, ${isOverdue ? '#ff9800' : '#2d5016'} 0%, ${isOverdue ? '#f57c00' : '#1a3009'} 100%); padding: 40px 30px; text-align: center;">
              <h1 style="color: white; margin: 0; font-size: 28px;">${isOverdue ? 'Payment Overdue' : 'Payment Reminder'}</h1>
            </td>
          </tr>
          <tr>
            <td style="padding: 40px 30px;">
              <h2 style="color: #1a1a1a; margin: 0 0 20px 0;">Dear ${invoice.tenantName},</h2>
              <p style="color: #666; line-height: 1.6; margin-bottom: 25px;">
                ${isOverdue
                  ? `Your rent payment for ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} is now overdue. Please submit payment as soon as possible to avoid late fees.`
                  : `This is a friendly reminder that your rent payment for ${getMonthName(invoice.billingMonth)} ${invoice.billingYear} is due on ${invoice.dueDate.toLocaleDateString()}.`
                }
              </p>

              <div style="background: #f9f9f9; padding: 20px; border-radius: 8px; margin-bottom: 25px; text-align: center;">
                <p style="color: #666; margin: 0 0 10px 0;">Amount Due</p>
                <p style="color: ${isOverdue ? '#ff9800' : '#2d5016'}; margin: 0; font-size: 32px; font-weight: 700;">$${invoice.balance.toFixed(2)}</p>
                ${!isOverdue ? `<p style="color: #666; margin: 10px 0 0 0; font-size: 13px;">Due: ${invoice.dueDate.toLocaleDateString()}</p>` : ''}
              </div>

              ${!isOverdue ? `
                <p style="color: #666; line-height: 1.6; margin-bottom: 15px;">
                  <strong>Remember:</strong> A $50 late fee will be applied to payments received after ${invoice.lateAfterDate.toLocaleDateString()}.
                </p>
              ` : ''}

              <p style="color: #666; line-height: 1.6;">
                If you have any questions or have already submitted payment, please contact us at office@m77ag.com or (970) 520-1807.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

module.exports = {
  generateMonthlyInvoice,
  autoGenerateInvoices,
  recordPayment,
  getAllInvoices,
  getInvoiceById,
  applyLateFees,
  sendPaymentReminders
};
